// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrgb6zj5LnNPoiKI2oBaWtsmXgGtdQn6s',
    appId: '1:9861213415:web:d11e5c27d69e393c58c642',
    messagingSenderId: '9861213415',
    projectId: 'artemis-mobile-7905c',
    authDomain: 'artemis-mobile-7905c.firebaseapp.com',
    storageBucket: 'artemis-mobile-7905c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmV_3RAuhFsGkarbqNYBhbJLFcuGmuJDc',
    appId: '1:9861213415:android:94912c4c8fdfe5dc58c642',
    messagingSenderId: '9861213415',
    projectId: 'artemis-mobile-7905c',
    storageBucket: 'artemis-mobile-7905c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcy9HI3nL_dE6hr-b-pbWLmfISySRYPg',
    appId: '1:9861213415:ios:be8f690b3cc9676d58c642',
    messagingSenderId: '9861213415',
    projectId: 'artemis-mobile-7905c',
    storageBucket: 'artemis-mobile-7905c.appspot.com',
    iosClientId: '9861213415-6ajajbhfejfhni7212015t427q2uvnf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.artemismobile',
  );
}
